# Generated by Django 6.0.3 on 2026-03-26 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='video_upload',
            field=models.FileField(blank=True, help_text='Upload a video file to automatically update the URL via UploadThing', null=True, upload_to='temp_uploads/'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='video_upload',
            field=models.FileField(blank=True, help_text='Upload a video file to automatically update the URL via UploadThing', null=True, upload_to='temp_uploads/'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='video_url',
            field=models.URLField(blank=True, help_text='The URL of the video (auto-populated if file is uploaded)'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='intro_video_url',
            field=models.URLField(blank=True, help_text='The URL of the video (auto-populated if file is uploaded)'),
        ),
    ]
