# Generated by Django 6.0.3 on 2026-03-27 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_branch_video_upload_campaign_video_upload_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='video_upload',
            field=models.FileField(blank=True, help_text='Upload a video file to automatically upload to UploadThing', null=True, upload_to='temp_uploads/'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='video_upload',
            field=models.FileField(blank=True, help_text='Upload a video file to automatically upload to UploadThing', null=True, upload_to='temp_uploads/'),
        ),
    ]
