# Generated by Django 6.0.3 on 2026-03-27 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_branch_video_upload_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='video_upload',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='video_upload',
        ),
        migrations.AlterField(
            model_name='branch',
            name='video_url',
            field=models.URLField(blank=True, help_text='Paste the UploadThing video URL here (upload at uploadthing.com/dashboard)'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='intro_video_url',
            field=models.URLField(blank=True, help_text='Paste the UploadThing video URL here (upload at uploadthing.com/dashboard)'),
        ),
    ]
