# Generated by Django 6.0.3 on 2026-03-27 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_video_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='video_upload',
            field=models.FileField(blank=True, help_text='Upload video to UploadThing', null=True, upload_to='temp_uploads/'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='video_upload',
            field=models.FileField(blank=True, help_text='Upload video to UploadThing', null=True, upload_to='temp_uploads/'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='video_url',
            field=models.URLField(blank=True, help_text='Video URL (auto-filled when uploading)'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='intro_video_url',
            field=models.URLField(blank=True, help_text='Video URL (auto-filled when uploading)'),
        ),
    ]
