# Generated by Django 6.0.3 on 2026-03-29 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_campaign_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Determines which published campaign is shown on the frontend home page.'),
        ),
    ]
